blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  root 'posts#index'

  get 'login'   => 'user_sessions#new'
  post 'login'  => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :author, :body, presence: true
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  has_many :comments
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:create, :destroy]

  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to @post,
                  notice: 'Comment was successfully created.'
    else
      redirect_to @post,
                  alert: 'Error creating comment.' + @comment.errors.full_messages.to_sentence
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post, alert: 'Comment successfully deleted!'
  end

private

  def comment_params
    params.require(:comment).permit(:author, :body, :email, :destroy)
  end

  def set_comment
    @post = Post.find(params[:post_id])
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
  def friendly_date(d)
    d.strftime("%B %e, %Y")
  end
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/comments/_comment.html.erb
<p><%= comment.author %> said:</p>

<blockquote>
  <%= comment.body %>
</blockquote>

<%= link_to 'Destroy', [comment.post, comment],
method: :delete, data: { confirm: 'Are you sure?'} %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Rails Crash Course Blog Tutorial</h1>

<%= yield %>

</body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
    <% @posts.each do |post| %>
    <h2><%= link_to post.title, post %></h2>
    <p><strong><em>Author:</strong></em> <%= post.author %></p>
    <p><em><%= friendly_date post.created_at %></em></p>
    <p><%= post.body %></p>
    <p>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete,
              data: { confirm: 'Are you sure?' } %>
    </p>
    <% end %>

<br />

<%= link_to 'New Post', new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
  <h2><%= @post.title %></h2>
  <p><strong><em>Author:</strong></em> <%= @post.author %></p>
  <p><%= @post.body %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h3>Comments</h3>

<%= render @post.comments %>

<h4>New Comment</h4>
<%= form_for [@post, @post.comments.build] do |f| %>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>