social/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  post 'follow/:id', to: 'users#follow', as: 'follow_user'

  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  root 'posts#index'
end

social/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
  belongs_to :user

  validates :user_id, presence: true
  validates :post_id, presence: true
end

social/app/models/image_post.rb
class ImagePost < Post
  validates :url, presence: true
end

social/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :user_id, presence: true
  validates :type, presence: true

  def cached_comment_count
    Rails.cache.fetch [self, "comment_count"] do
      comments.size
    end
  end
end

social/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :leader, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

social/app/models/text_post.rb
class TextPost < Post
  validates :body, presence: true
end

social/app/models/user.rb
class User < ActiveRecord::Base
  has_many :subscriptions, foreign_key: :follower_id,
                          dependent: :destroy
  has_many :leaders, through: :subscriptions

  has_many :reverse_subscriptions, foreign_key: :leader_id,
                                   class_name: 'Subscription',
                                   dependent: :destroy
  has_many :followers, through: :reverse_subscriptions

  has_many :posts, dependent: :destroy
  has_many :text_posts, dependent: :destroy
  has_many :image_posts, dependent: :destroy
  has_many :comments

  has_secure_password

  validates :email, presence: true, uniqueness:true

  def following?(leader)
    leaders.include? leader
  end

  def follow!(leader)
    if leader != self && !following?(leader)
      leaders << leader
    end
  end

  def timeline_user_ids
    leader_ids + [id]
  end
end

social/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user!
    redirect_to login_path unless current_user
  end
end

social/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      redirect_to post_path(@comment.post_id), notice: 'Comment was successfully created!'
    else
      redirect_to post_path(@comment.post_id), alert: 'Error creating comment!'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if @comment.destroy
      redirect_to post_path(@comment.post_id), notice: 'Comment was successfully destroyed!'
    else
      redirect_to post_path(@comment.post_id), alert: 'Error destroying comment!'
    end
  end


private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

social/app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  def new
    @image_post = ImagePost.new
  end

  def create
    @image_post = current_user.image_posts.build(image_post_params)
    if @image_post.save
      redirect_to post_path(@image_post), notice: "Post created!"
    else
      render :new, alert: "Error creating post."
    end
  end

  def edit
    @image_post = current_user.image_posts.find(params[:id])
  end

  def update
    @image_post = current_user.image_posts.find(params[:id])
    if @image_post.update(image_post_params)
      redirect_to post_path(@image_post), notice: "Post successfully updated!"
    else
      render :edit, alert: "Error updating post!"
    end
  end

private

  def image_post_params
    params.require(:image_post).permit(:title, :url, :body)
  end
end

social/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    user_ids = current_user.timeline_user_ids

    @posts = Post.includes(:user).where(user_id: user_ids)
                .paginate(page: params[:page], per_page: 5)
                .order("created_at DESC")
  end

  def show
    @post = Post.includes(comments: [:user]).find(params[:id])
    @can_moderate = (current_user == @post.user)
  end
end

social/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    flash[:notice] = "Welcome back, #{user.name}!"
    redirect_to(session[:intended_url => true] || user)
    session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You're now signed out!"
  end
end

social/app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
  def new
    @text_post = TextPost.new
  end

  def create
    @text_post =
      current_user.text_posts.build(text_post_params)
      if @text_post.save
        redirect_to post_path(@text_post),
                      notice: "Post created!"
      else
        render :new, alert: "Error creating post."
      end
  end

  def edit
    @text_post = current_user.text_posts.find(params[:id])
  end

  def update
    @text_post = current_user.text_posts.find(params[:id])
    if @text_post.update(text_post_params)
      redirect_to post_path(@text_post), notice: "Post successfully updated!"
    else
      render :edit, alert: "Error updating post!"
    end
  end

private

  def text_post_params
    params.require(:text_post).permit(:title, :body)
  end
end

social/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :follow

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url,
        notice: "Welcome to the site!"
    else
      render "new"
    end
  end

  def follow
    @user = User.find(params[:id])

    if current_user.follow!(@user)
      redirect_to @user, notice: "Follow successful!"
    else
      redirect_to @user, alert: "Error following."
    end
  end



private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

social/app/helpers/application_helper.rb
module ApplicationHelper
end

social/app/helpers/comments_helper.rb
module CommentsHelper
end

social/app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

social/app/helpers/posts_helper.rb
module PostsHelper
end

social/app/helpers/sessions_helper.rb
module SessionsHelper
end

social/app/helpers/text_posts_helper.rb
module TextPostsHelper
end

social/app/helpers/users_helper.rb
module UsersHelper
end

social/app/views/comments/_comment.html.erb
<% cache [comment, @can_moderate] do %>
  <p><em><strong><%= comment.user.name %></em> said:</em></p>
  <p><%= comment.body %></p>
  <% if @can_moderate %>
  <p>
  <%= link_to 'Delete', comment_path(comment), method: :delete,
                         data: { confirm: 'Are you sure?' } %>
  </p>
  <% end %>
<% end %>

social/app/views/image_posts/_form.html.erb
<%= form_for @image_post do |f| %>
  <% if @image_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_post.errors.count, "error") %> prohibited you from posting:</h2>

      <ul>
      <% @image_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      <% end %>
<div class="row">
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :title, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :title %>
        </div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :url, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :url %>
        </div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :body, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_area :body %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.submit class: "button" %>
          <%= link_to 'Cancel', :back, class: 'button' %>
        </div>
      </div>
    </div>
  </div>

<% end %>

social/app/views/image_posts/_image_post.html.erb
<div class="row">
  <div class="small-3 column">
    <h3>
      <%= image_post.title %>
    </h3>
     <%= link_to"#{time_ago_in_words image_post.created_at} ago", post_path(image_post) %>
  </div>

  <div class="small-9 column panel radius">
    <p><em>By <%= link_to image_post.user.name, image_post.user %></em></p>
    <%= image_tag image_post.url, class: 'img-responsive' %>
    <%= image_post.body %>
        <p><%= pluralize image_post.cached_comment_count %></p>

     <% if image_post.user == current_user %>
    <p>
      <%= link_to 'Edit', edit_image_post_path(image_post), class: 'button' %>
    </p>
    <% end %>
  </div>
</div>

social/app/views/image_posts/edit.html.erb
<div class="row">
  <h1>Edit Image Post</h1>
</div>

<%= render 'form' %>

social/app/views/image_posts/new.html.erb
<div class="row">
  <h1>New Image Post</h1>
</div>

<%= render 'form' %>

social/app/views/layouts/_header.html.erb
<div class="large-12 columns">
    <nav class="top-bar" data-topbar="" role="navigation" data-options="is_hover: false">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to 'Stok Social', root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>


<section class="top-bar-section">

    <!-- Right Nav Section -->
    <ul class="right">
        <% if current_user %>
          <li class="active">
          <%= link_to 'Profile', current_user %>
          </li>
          <li class="active">
          <%= link_to 'Log Out', logout_path, method: :delete %>
          </li>
        <% else %>
          <li class="active">
          <%= link_to 'Log In', login_path %>
          </li>
          <li class="active">
          <%= link_to 'Sign Up', signup_path %>
          </li>
        <% end %>
      <li class="divider hide-for-small"></li>
      <li class="has-dropdown"><a>Main Item 1</a>
        <ul class="dropdown"><li class="title back js-generated"><h5><a href="javascript:void(0)">Back</a></h5></li>
          <li><label>Dropdown Level 1 Label</label></li>
          <li class="has-dropdown"><a>Dropdown Level 1a</a>

            <ul class="dropdown"><li class="title back js-generated"><h5><a href="javascript:void(0)">Back</a></h5></li>
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a>Dropdown Level 2c</a>

                <ul class="dropdown"><li class="title back js-generated"><h5><a href="javascript:void(0)">Back</a></h5></li>
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><label>Dropdown Level 1 Label</label></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all →</a></li>
        </ul>
      </li>
    </ul>

  </section></nav>

  </div><br />

social/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Stok Social" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <br />

    <div class="row">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
        <% end %>
      <% end %>
    </div>


    <%= yield %>


  </body>
</html>

social/app/views/posts/index.html.erb
<div class="row">
  <h1>Post</h1>
</div>
<%= render @posts %>
<%= will_paginate @posts %>
 <div class="row">
  <p><%= link_to "New Text Post", new_text_post_path, class: 'button' %></p>
  <p><%= link_to "New Image Post", new_image_post_path, class: 'button' %></p>
  </div>

social/app/views/posts/show.html.erb
<div class="row">
<h1>Post</h1>
</div>

<div class="row">
  <div class="small-8">
      <%= render @post %>
    <div class="small-4">
      <h3>Comments</h3>
      <% cache [@post, 'comments', @can_moderate] do %>
        <%= render @post.comments %>
      <% end %>
  </div>
</div>
<div class="row">
  <h4>New Comment</h4>
  <%= form_for @post.comments.build do |f| %>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :body, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_area :body %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.hidden_field :post_id %>
          <%= f.submit :class => 'button expand' %>
        </div>
      </div>
    </div>
  <% end %>

social/app/views/text_posts/_form.html.erb
<%= form_for @text_post do |f| %>
  <% if @text_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_post.errors.count, "error") %> prohibited you from posting:</h2>

      <ul>
      <% @text_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      <% end %>
<div class="row">
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :title, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :title %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :body, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_area :body %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.submit class: "button" %>
          <%= link_to 'Cancel', :back, class: 'button' %>
        </div>
      </div>
    </div>
  </div>

<% end %>

social/app/views/text_posts/_text_post.html.erb
<% cache text_post do %>
<div class="row">
  <div class="small-3 column">
    <h3>
      <%= text_post.title %>
    </h3>
    <%= link_to("#{time_ago_in_words text_post.created_at} ago", post_path(text_post)) %>
  </div>

  <div class="small-9 column panel radius">
    <p><em>By <%= link_to text_post.user.name, text_post.user %></em></p>

    <p><%= sanitize text_post.body %></p>
    <p><%= pluralize text_post.cached_comment_count, "Comment" %></p>
  <% end %>
    <% if text_post.user == current_user %>
    <p>
      <%= link_to 'Edit', edit_text_post_path(text_post), class: 'button' %>
    </p>
    <% end %>
  </div>
</div>

social/app/views/text_posts/edit.html.erb
<div class="row">
  <h1>Edit Text Post</h1>
</div>

<%= render 'form' %>

social/app/views/text_posts/new.html.erb
<div class="row">
  <h1>New Text Post</h1>
</div>

<%= render 'form' %>

social/app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited you from signing up:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :email, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :email %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :password, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.password_field :password %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :password_confirmation, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.password_field :password_confirmation %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.submit :class => 'button expand' %>
        </div>
      </div>
    </div>
  </div>

<% end %>

social/app/views/users/show.html.erb
<div class="row">
<h1>User</h1>
</div>

<p><%= @user.name %></p>

<%= link_to "Follow", follow_user_path(@user), method: :post, class: "button" %>
<h2>Posts</h2>
<%= render @posts %>

<%= link_to "Home", root_path, class: 'button'  %>